# Dockerfile.prod
FROM eclipse-temurin:17-jdk as builder
WORKDIR /app
COPY pom.xml mvnw ./
COPY .mvn .mvn
COPY src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre as prod
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
